### ISSUE TITLE
Applications running under wine cant access internet!

### ISSUE THREAD

**Issue by RebornOfc** [Android-PowerUser/Windroid_11#4]
I've tested with some games, and seems like no application running under wine64 can access internet.

Wine 8.7

**Comment by Android-PowerUser** [comment]
That can't be the case, because Steam also runs on Wine and has internet... Maybe it's because of Wine 8.7 As you know the original installed is 8.0.0. The sed permission denied probably comes because netsockets (don't work. This can sometimes be a problem (but not always) but cannot be solved without real root. The sed permission denied probably comes because netsockets (shared memory) don't work. This can sometimes be a problem (but not always) but cannot be solved without real root.

**Comment by RebornOfc** [comment]
Sure I will try with older versions of wine.

**Comment by RebornOfc** [comment]
Ok, I realized that I was indeed using Wine 8.0, (I thought it was 8.7 because I confused myself because I have tried many "windows emulators on termux" and one prompts you to choose the wine version), so I thought I had choosen wine 8.7 here.

I did a fresh reinstall and still can't access internet on the application.

I'm trying to install some windows apps to check internet connection, to see if it is a global issue, but the installation always hangs on the last tick.

**Comment by RebornOfc** [comment]
Well I cant get Steam to open, and installing MSI on wine seems to not work, do you know any method I can use to check internet connection? (Or an internet checker app that is EXE and not MSI)

**Comment by Android-PowerUser** [comment]
Please note that it may take 2 minutes to start Steam. The internet should actually work in exe and msi. I can't explain it...

I've had a problem with Box64 before. Maybe you updated it. You can try different versions if you type `apt install box64-android=0.2.3+20230603.4f1cefe-1` or other versions. You can change the version and have a list here: [https://github.com/ryanfortner/box64-debs/tree/master/debian](https://github.com/ryanfortner/box64-debs/tree/master/debian)

**Comment by Android-PowerUser** [comment]
Is there an update on the topic?

**Comment by Android-PowerUser** [comment]
If the internet works otherwise in Windroid 11, which you notice in the terminal, then it's probably something you need to ask Wine developers.
